config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  namespace :admin do
      resources :users
      resources :carts
      resources :cart_items
      resources :items
      resources :orders
      resources :order_items

      root to: "users#index"
    end
  
  # Below : Devise
  devise_for :users
  resources 'items'
  resources 'users', only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Below : Stripe
  resources :charges
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show 
    @user = current_user
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(params.require(:user).permit(
      :first_name, :last_name, :description, :address, :zipcode)
    )
    redirect_to user_path(@user)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_update_form.html.erb
<div class ="container col-7">
<div class="row judstify-center">

<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "Ajoutez votre photo" %>
<% end %>
</div>
</div>
<br>


<%= form_with(model: user, local: true, method: :put) do |update| %>

  <div class="form-group">
    <%= update.text_field :first_name, class:"form-control", placeholder:"Prénom" %>
  </div>

  <div class="form-group">
    <%= update.text_field :last_name, class:"form-control", placeholder:"Nom" %>
  </div>

  <div class="form-group">
    <%= update.email_field :email, class:"form-control", placeholder:"email" %>
  </div>

  <div class="form-group">
    <%= update.text_area :description, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="form-group">
    <%= update.text_area :address , class:"form-control", placeholder:"Adresse" %>
  </div>

  <div class="form-group">
    <%= update.text_field :zipcode, class:"form-control", placeholder:"Code Postal" %>
  </div>

  <div class="actions text-center">
    <button type="submit" class="btn btn-primary">Editer mes informations</button>
  </div>
<% end %>

app/views/users/edit.html.erb
<br>
<br>
<br class="container">
<div class="row justify-center">
  <div class="col-3"></div>
  <div class="col-6">
    <h1 class="display-5-selection text-center">Editer votre profil</h1>

    <%= render 'update_form', user: @user %>

    <div class="text-center mt-4">
      <%= link_to 'Voir mon profil', @user, class:"btn btn-primary mr-4"%>
      <%= link_to "Page d'accueil", root_path, class:"btn btn-secondary"%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<html>

<div class='container'>

 <h1 class="display-4-selection text-center my-5">Mon Profil</h1>

<iframe src="http://www.inveo-conseil.fr" 
                                height="300" width="400"> 
    </iframe> 

  <div class="row justify-content-center">
    <div class="card border-primary">
      <div class="card-header">
        <p class="h3 text-center"> <%= @user.first_name %> <%= @user.last_name %></p>
      </div>

      <h3 class="text-center">Votre photo de profil</h3>
          <%if @user.avatar.attached?%>
            <%= image_tag @user.avatar, alt: 'avatar' %>
          <%else%>
            <p>=== Vous n'avez pas encore de photo de profil ===</p>
          <%end%> 

      <div class="card-body text-primary">
        <h5 class="card-title text-center">------------ Mes informations ------------ </h5>
        <p class="card-text text-center"><span class="h6 text-center">Ma description:</span><br> <span class="ml-3 text-center"><%= @user.description %></span><br></p>
          <p class="card-text text-center"><span class="h6 text-center">Mon email:</span><br> <span class="ml-3 text-center" ><%= @user.email %></span><br></p><br>
          <p class="card-text text-center"><span class="h6 text-center">Mon adresse:</span><br> <span class="text-center"><%= @user.address %><br></span><br></p>
          <p class="card-text text-center"><span class="h6 text-center">Mon code postal:</span><br> <span class="ml-3"><%= @user.zipcode %><br></span><br></p>

      </div>
    </div>
  </div>
  <br>
  <div class="text-center">
    <%= link_to "Editer mon profil", edit_user_path(current_user), class: "btn btn-primary mr-5" %>
    <%= link_to 'Retour Accueil', root_path, class:"btn btn-secondary" %>
    <br><br><br>

  </div>
</div>
</html>