config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  namespace :admin do
      resources :users
      resources :carts
      resources :cart_items
      resources :items
      resources :orders
      resources :order_items

      root to: "users#index"
    end
  
  # Below : Devise
  devise_for :users
  resources 'items'
  resources 'users', only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Below : Stripe
  resources :charges
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items

  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 200 }
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image_url, presence: true
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  include ApplicationHelper

  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  end

  def create
    @item = Item.create
  end

  def edit
  end

  def update
    @item = Item.find(params[:id])
    @item.update
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Front page</title>
</head>
<body>

  <!------JUMBOTRON------>

  <section>
    <div class="jumbotron jumbotron-fluid">
      <div class="container text-center">
        <h1 class="display-4">PUUURFECT</h1>
        <h2 class="h3 mb-3">Des images qui vous feront ronronner de bonheur !</h2>
      </div>
    </div>
  </section>

  <!------INDEX------>

  <h3 class="cute_kittens text-center"> ❤️ Tous nos chatons trop trop mignons ❤️ </h3><br>

  <div class="container">
    <div class="row">
      <% @items.each do |item| %>

        <div class="col col-6">
          <div class="card border-primary mb-3" style="max-width: 20rem;">
            <div class="card-body">
              <a href="<%= item_path(item.id) %>">
                <img src="<%= item.image_url %>" class="card-img-top" alt="image of the cat" style="height: 200px; width: 100%; display: block;">
              </a>
              <h4 class="card-title text-center"><%= item.title %></h4>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>



</body>
</html>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>



  <!------JUMBOTRON------>

  <section>
    <div class="jumbotron jumbotron-fluid">
      <div class="container text-center">
        <h1 class="display-4">PUUURFECT</h1>
        <h2 class="h3 mb-3">Des images qui vous feront ronronner de bonheur !</h2>
      </div>
    </div>
  </section>


  <div class="container"


  <div class="card border-primary md-8" style="max-width: 80%;">
    <div class="card-header"><img src="<%= @item.image_url %>" class="element_picture" alt="kitty kitty"></div>
    <div class="card-body">
      <h3 class="card-title"><%= @item.title%></h3>
      <p class="card-text"><%= @item.description %></p>
      <h4 class="product-price"><small class="text-muted"><%= @item.price%> €</small></h4>
      <% if user_signed_in? %>
          <%= link_to "Ajouter au panier", root_path, class: "show-button"%>
      <% end %>
    </div>
    </div>
  </div>

  
</div>

</body>
</html>